# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GoReleaser Action'
description: 'GitHub Action for GoReleaser, a release automation tool for Go projects'
author: 'goreleaser'
branding:
  color: 'green'
  icon: 'package'

inputs:
  distribution:
    description: 'GoReleaser Distribution (goreleaser or goreleaser-pro)'
    default: 'goreleaser'
    required: false
  version:
    description: 'GoReleaser version'
    required: false
  version-file:
    description: |
      Gets the version of GoReleaser to use from a file.
      The path must be relative to the root of the project, or the `workdir` if defined.
      This parameter supports `.tool-versions` files.
      Only works with `install-mode: binary` (the default).
    required: false
  args:
    description: 'Arguments to pass to GoReleaser'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install GoReleaser'
    default: 'false'
    required: false

outputs:
  artifacts:
    description: 'Build result artifacts'
  metadata:
    description: 'Build result metadata'

runs:
  using: 'node24'
  main: 'dist/index.js'
