#!/usr/bin/env bash
set -euo pipefail

if ! command -v jq &> /dev/null; then
  echo "Error: jq is required but not installed."
  exit 1
fi
# don't go back further than v0.180
MIN_MAJOR=0
MIN_MINOR=182
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="$DIR/src/checksums.ts"
FLAT_FILE=$(mktemp)
trap 'rm -f "$FLAT_FILE"' EXIT

echo "Loading existing checksums..."
if [ -f "$OUT_FILE" ]; then
  EXISTING_JSON=$(grep -v "^//" "$OUT_FILE" | sed -e 's/^export const checksums.*= //' -e 's/;$//' || echo "{}")
  if ! echo "$EXISTING_JSON" | jq empty >/dev/null 2>&1; then
    echo "[WARNING] Existing checksums.ts is not valid JSON. Starting fresh."
    EXISTING_JSON="{}"
  fi
else
  EXISTING_JSON="{}"
fi

EXISTING_KEYS=$(echo "$EXISTING_JSON" | jq -r 'keys[]' 2>/dev/null || echo "")
FETCHED_URLS=""

fetch_checksums() {
  local tag=$1
  local repo=$2

  if [ "$tag" = "null" ] || [ -z "$tag" ]; then
    return
  fi

  local clean_v
  local major
  local minor
  clean_v=$(echo "$tag" | sed 's/^v//' | sed 's/-pro$//' | sed 's/~pro$//')
  major=$(echo "$clean_v" | cut -d. -f1 || echo "")
  minor=$(echo "$clean_v" | cut -d. -f2 || echo "")

  if [[ "$major" =~ ^[0-9]+$ ]] && [[ "$minor" =~ ^[0-9]+$ ]]; then
    if [ "$major" -eq "$MIN_MAJOR" ] && [ "$minor" -lt "$MIN_MINOR" ]; then
      return
    fi
  fi

  if echo "$EXISTING_KEYS" | grep -F -q -x "$tag"; then
    echo "Checksums for $tag ($repo) already exist, skipping."
    return
  fi

  local url="https://github.com/goreleaser/$repo/releases/download/$tag/checksums.txt"

  # Check if we already fetched this exact url
  if echo " $FETCHED_URLS " | grep -q " $url "; then
    return
  fi

  echo "Fetching checksums for $tag ($repo)..."
  local checksums
  # Try the standard checksums.txt, or fallback to the older naming convention
  checksums=$(curl -sfL "$url" || curl -sfL "https://github.com/goreleaser/$repo/releases/download/$tag/${repo}_checksums.txt" || true)

  if [ -z "$checksums" ]; then
    echo "[WARNING] Failed to fetch checksums for $tag at $url"
    return
  fi

  checksums=$(echo "$checksums" | tr -d '\r')

  FETCHED_URLS="$FETCHED_URLS $url "

  while read -r sha256 filename; do
    if [ -z "$sha256" ] || [ -z "$filename" ]; then continue; fi
    echo "$tag $filename $sha256" >> "$FLAT_FILE"
  done <<< "$checksums"
}

echo "Fetching all GoReleaser tags..."
GORELEASER_TAGS=$(curl -sfL "https://goreleaser.com/releases.json" | jq -r '.[].tag_name')
for tag in $GORELEASER_TAGS; do
  fetch_checksums "$tag" "goreleaser"
done

echo "Fetching all GoReleaser Pro tags..."
PRO_TAGS=$(curl -sfL "https://goreleaser.com/releases-pro.json" | jq -r '.[].tag_name')
for tag in $PRO_TAGS; do
  # Pro tags older than 2.7.0 are resolved with a `-pro` suffix by the action
  clean_v=$(echo "$tag" | sed 's/^v//' | sed 's/-pro$//' | sed 's/~pro$//')
  major=$(echo "$clean_v" | cut -d. -f1 || echo "")
  minor=$(echo "$clean_v" | cut -d. -f2 || echo "")

  if [[ "$major" =~ ^[0-9]+$ ]] && [[ "$minor" =~ ^[0-9]+$ ]]; then
    if [ "$major" -lt 2 ] || { [ "$major" -eq 2 ] && [ "$minor" -lt 7 ]; }; then
      if [[ "$tag" != *"-pro" ]]; then
        tag="${tag}-pro"
      fi
    fi
  fi

  fetch_checksums "$tag" "goreleaser-pro"
done

echo "Merging new checksums with existing..."
NEW_JSON=$(jq -n -R '
  reduce inputs as $line ({};
    ($line | split(" ")) as $parts |
    if ($parts | length) >= 3 then
      .[$parts[0]][$parts[1]] = $parts[2]
    else
      .
    end
  )
' < "$FLAT_FILE")

MERGED_JSON=$(echo "$EXISTING_JSON" | jq --argjson new "$NEW_JSON" '. * $new')
SORTED_JSON=$(echo "$MERGED_JSON" | jq -r 'keys[]' | sort -rV | jq -R . | jq -s 'map(select(length > 0))' | jq --argjson data "$MERGED_JSON" 'map({key: ., value: $data[.]}) | from_entries')

rm -f "$OUT_FILE"
touch "$OUT_FILE"
{
  echo "// This file contains sha256 checksums of GoReleaser binaries."
  echo "// Auto-generated by update-checksums.sh"
  echo -n "export const checksums: Record<string, Record<string, string>> = "
  echo "$SORTED_JSON;"
} >> "$OUT_FILE"

echo -e "\nSuccessfully updated src/checksums.ts!"
